-- L1_001__copy_into_bronze.sql
-- Run after uploading files to stages

USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;

USE DATABASE SOUDAH_DB;
USE SCHEMA BRONZE;

-- BOOKING CSV
COPY INTO BOOKINGS_RAW
FROM (
  SELECT *
  FROM @STG_BOOKINGS t
)
FILE_FORMAT = (FORMAT_NAME = SOUDAH_DB.UTIL.FF_CSV_RAW)
ON_ERROR = CONTINUE;

-- PAYMENTS CSV
COPY INTO PAYMENTS_RAW
FROM (
  SELECT *
  FROM @STG_PAYMENTS t
)
FILE_FORMAT = (FORMAT_NAME = SOUDAH_DB.UTIL.FF_CSV_RAW)
ON_ERROR = CONTINUE;

-- POS CSV
COPY INTO POS_TXN_RAW
FROM (
  SELECT *
  FROM @STG_POS t
)
FILE_FORMAT = (FORMAT_NAME = SOUDAH_DB.UTIL.FF_CSV_RAW)
ON_ERROR = CONTINUE;

-- HOUSEKEEPING JSONL
COPY INTO HOUSEKEEPING_EVENTS_RAW
FROM (
  SELECT
    $1:event_id::STRING,
    $1:task_id::STRING,
    $1:event_time_raw::STRING,
    $1:property_code::STRING,
    $1:room_code::STRING,
    $1:status::STRING,
    $1:staff_id_raw::STRING,
    $1:priority_raw::STRING,
    $1:notes::STRING,
    $1:payload,
    METADATA$FILENAME::STRING,
    current_timestamp()
  FROM @STG_HOUSEKEEPING
)
FILE_FORMAT = (FORMAT_NAME = SOUDAH_DB.UTIL.FF_JSONL_RAW)
ON_ERROR = CONTINUE;

-- MAINTENANCE JSONL
COPY INTO MAINTENANCE_EVENTS_RAW
FROM (
  SELECT
    $1:event_id::STRING,
    $1:ticket_id::STRING,
    $1:event_time_raw::STRING,
    $1:property_code::STRING,
    $1:asset_tag::STRING,
    $1:severity_raw::STRING,
    $1:status_raw::STRING,
    $1:issue_text::STRING,
    $1:downtime_minutes_raw::STRING,
    $1:payload,
    METADATA$FILENAME::STRING,
    current_timestamp()
  FROM @STG_MAINTENANCE
)
FILE_FORMAT = (FORMAT_NAME = SOUDAH_DB.UTIL.FF_JSONL_RAW)
ON_ERROR = CONTINUE;

-- Quick row counts
SELECT 'BOOKINGS_RAW' AS table_name, COUNT(*) FROM BOOKINGS_RAW
UNION ALL
SELECT 'PAYMENTS_RAW', COUNT(*) FROM PAYMENTS_RAW
UNION ALL
SELECT 'POS_TXN_RAW', COUNT(*) FROM POS_TXN_RAW
UNION ALL
SELECT 'HOUSEKEEPING_EVENTS_RAW', COUNT(*) FROM HOUSEKEEPING_EVENTS_RAW
UNION ALL
SELECT 'MAINTENANCE_EVENTS_RAW', COUNT(*) FROM MAINTENANCE_EVENTS_RAW;