-- V1_002__bronze_file_formats_and_stages.sql
-- File formats and internal stages (manual upload target)

USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;

USE DATABASE SOUDAH_DB;
USE SCHEMA UTIL;

CREATE OR REPLACE FILE FORMAT FF_CSV_RAW
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  TRIM_SPACE = FALSE
  EMPTY_FIELD_AS_NULL = FALSE
  NULL_IF = ('\\N')
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

CREATE OR REPLACE FILE FORMAT FF_JSONL_RAW
  TYPE = JSON
  STRIP_OUTER_ARRAY = FALSE;

-- Stages live in BRONZE schema
USE SCHEMA BRONZE;

CREATE OR REPLACE STAGE STG_BOOKINGS
  FILE_FORMAT = SOUDAH_DB.UTIL.FF_CSV_RAW;

CREATE OR REPLACE STAGE STG_PAYMENTS
  FILE_FORMAT = SOUDAH_DB.UTIL.FF_CSV_RAW;

CREATE OR REPLACE STAGE STG_POS
  FILE_FORMAT = SOUDAH_DB.UTIL.FF_CSV_RAW;

CREATE OR REPLACE STAGE STG_HOUSEKEEPING
  FILE_FORMAT = SOUDAH_DB.UTIL.FF_JSONL_RAW;

CREATE OR REPLACE STAGE STG_MAINTENANCE
  FILE_FORMAT = SOUDAH_DB.UTIL.FF_JSONL_RAW;