-- V1_001__init_db_and_schemas.sql
-- Create database and schemas for Soudah Peaks

USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE DATABASE IF NOT EXISTS SOUDAH_DB;

CREATE SCHEMA IF NOT EXISTS SOUDAH_DB.BRONZE;
CREATE SCHEMA IF NOT EXISTS SOUDAH_DB.SILVER;
CREATE SCHEMA IF NOT EXISTS SOUDAH_DB.GOLD;
CREATE SCHEMA IF NOT EXISTS SOUDAH_DB.UTIL;