transformations:
  outputs:
    dev:
      account: YNXFYXC-IL57355
      database: SOUDAH_DB
      password: MjMedallion@2026
      role: SYSADMIN
      schema: UTIL
      threads: 1
      type: snowflake
      user: MRUTYUNJAYA.SAHOO
      warehouse: COMPUTE_WH
  target: dev
